language: node_js
node_js: stable
sudo: required
dist: trusty
branches:
  only:
  - master
  - develop
install:
  - npm cache verify
  - npm install
script:
  - npm run test:unit
if: branch = develop
  script:
    - npm run build
    - node upload.js