language: node_js
node_js: stable
sudo: required
dist: trusty
install:
  - npm cache verify
  - npm install
env:
  - "ACCOUNT_KEY_DEV"
  - "ACCOUNT_NAME_DEV"
script:
  - npm run test:unit
  - npm run build
  - npm run upload