language: node_js
node_js: stable
sudo: required
dist: trusty
install:
  - npm cache verify
  - npm install
script:
  - npm run test:unit
  - npm run build
deploy:
  provider: azure_web_apps
  on: vueStarter
  username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
  password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
  site: azure_deployment_sitename       # If AZURE_WA_SITE isn't set